set_case_analysis {b 11} -objects [get_ports test_aa[1:0]]
set_case_analysis {b 111101} -objects [get_ports test_bb]
set_case_analysis {b 000} -objects [get_ports test_cc]
set_case_analysis 1 -objects [get_ports test_dd]
set_case_analysis 0 -objects [get_ports test_ee]
set_case_analysis {b 101} -objects [get_ports test_ff]
set_case_analysis {b 101} -objects [get_ports test_b1[4:2]]
set_case_analysis {b 101} -objects [get_ports test_b2[4:0]]
set_case_analysis {b 010} -objects [get_ports test_b3[3:5]]
set_case_analysis {b 010} -objects [get_ports test_b4[1:5]]
set_case_analysis {b 010} -objects [get_ports test_b5[1][4:2]]
set_case_analysis {b 010} -objects [get_ports test_b6[1:0][3:0]]
set_case_analysis {b 10111111} -objects [get_ports test_b7[4:2]]
set_case_analysis {b 11111011} -objects [get_ports test_b8[4:0]]
